version: '3'
services:
  php:
    image: hub.dbztech.com/dbz-tech-website:1.0.0
    ports:
      - 8090:80
    networks:
      - dmz
    restart: always

networks:
  dmz:
    external:
      name: dbztech
